### ISSUE TITLE
代码高亮不生效

### ISSUE THREAD

**Issue by yangweijie** [rocky-git/E-admin#10]
![image](https://user-images.githubusercontent.com/1614114/154825056-ef77e0a4-b4f2-488f-ad7c-672358f79e26.png)
看到  vendor 里有babel-config 里配置了 prismjs
但是自己写组件 却不显示 内容都没了。

![image](https://user-images.githubusercontent.com/1614114/154825128-e44ff013-c94c-45e6-93f4-7706c5443ea9.png)

**Comment by rocky-git** [comment]
\Eadmin\component\basic\Html::code('这里是你高亮代码'); //php代码

<highlight code="高亮代码"></highlight> //前端组件代码

交流QQ群 579150457

**Comment by rocky-git** [comment]
`<highlight code="高亮代码""></highlight>`
