### ISSUE TITLE
咨询一下关于抛出异常的问题.

### ISSUE THREAD

**Issue by Abbotton** [rocky-git/E-admin#12]
我在本地测试环境中, 主动抛出异常, 在`runtime/log`以及`runtime/admin/log`目录中均没有发现错误日志.但是通过`Log::error('测试')`是可以记录日志的.

还有一个问题, 如果接口出现异常, 那接口返回数据是空的, 及时debug以及显示错误信息开启, 也没有返回任何信息, 非常不好调试, 见下图:
![image](https://user-images.githubusercontent.com/16308633/157603321-ad564329-59f2-46eb-a188-65037b2fd751.png)
![image](https://user-images.githubusercontent.com/16308633/157603367-a4f50765-a39e-4a4a-a597-ba215f889681.png)

**Comment by rocky-git** [comment]
抛出异常正常有错误页的
![image](https://user-images.githubusercontent.com/44958386/158089507-3219f55c-9b05-4d1a-bbcb-7ba574bbd10a.png)

**Comment by Abbotton** [comment]
可能是我本地环境的问题.
