### ISSUE TITLE
grid 自定义工具可以打开 from 吗？

### ISSUE THREAD

**Issue by yzh52521** [rocky-git/E-admin#2]
grid 自定义工具可以打开 from 吗？
我想做个导入 功能

**Comment by rocky-git** [comment]
```php
$grid->tools([
            Button::create('批量导入')
                ->typePrimary()->sizeSmall()
                ->upload(url('need/export',['project_id'=>$project_id])),
            Button::create('下载导入模板')
                ->sizeSmall()
                ->redirect('https://'.$this->request->host().'/需求导入.xlsx')
        ]);

```

**Comment by rocky-git** [comment]
```php
$grid->tools([
            Button::create('打开form')
                ->dialog()
                ->title('表单标题')
                ->form($this->form())
        ]);
```

**Comment by yzh52521** [comment]
> ```
> $grid->tools([
>             Button::create('批量导入')
>                 ->typePrimary()->sizeSmall()
>                 ->upload(url('need/export',['project_id'=>$project_id])),
>             Button::create('下载导入模板')
>                 ->sizeSmall()
>                 ->redirect('https://'.$this->request->host().'/需求导入.xlsx')
>         ]);
> ```

导入成功了 返回什么？ 弹出成功列表页才可以刷新

**Comment by rocky-git** [comment]
QQ群 579150457

**Comment by rocky-git** [comment]
admin_success_message('导入成功')->refresh();
